/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const GbfsVersions = t.iface([], {
  "data": "Data",
  "last_updated": "string",
  "ttl": "number",
  "version": "GbfsVersionsVersion",
  [t.indexKey]: "any",
});

export const Data = t.iface([], {
  "versions": t.array("VersionElement"),
});

export const VersionElement = t.iface([], {
  "url": "string",
  "version": "VersionVersion",
  [t.indexKey]: "any",
});

export const VersionVersion = t.union(t.lit("1.0"), t.lit("1.1"), t.lit("2.0"), t.lit("2.1"), t.lit("2.2"), t.lit("2.3"), t.lit("3.0"));

export const GbfsVersionsVersion = t.lit("3.0");

const exportedTypeSuite: t.ITypeSuite = {
  GbfsVersions,
  Data,
  VersionElement,
  VersionVersion,
  GbfsVersionsVersion,
};
export default exportedTypeSuite;
