/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Manifest = t.iface([], {
  "data": "Data",
  "last_updated": "Date",
  "ttl": "number",
  "version": "ManifestVersion",
  [t.indexKey]: "any",
});

export const Data = t.iface([], {
  "datasets": t.array("Dataset"),
});

export const Dataset = t.iface([], {
  "system_id": "string",
  "versions": t.array("VersionElement"),
  [t.indexKey]: "any",
});

export const VersionElement = t.iface([], {
  "url": "string",
  "version": "VersionVersion",
  [t.indexKey]: "any",
});

export const VersionVersion = t.union(t.lit("1.0"), t.lit("1.1"), t.lit("2.0"), t.lit("2.1"), t.lit("2.2"), t.lit("2.3"), t.lit("3.0"));

export const ManifestVersion = t.lit("3.0");

const exportedTypeSuite: t.ITypeSuite = {
  Manifest,
  Data,
  Dataset,
  VersionElement,
  VersionVersion,
  ManifestVersion,
};
export default exportedTypeSuite;
