/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const SystemRegions = t.iface([], {
  "data": "Data",
  "last_updated": "Date",
  "ttl": "number",
  "version": "Version",
  [t.indexKey]: "any",
});

export const Data = t.iface([], {
  "regions": t.array("Region"),
  [t.indexKey]: "any",
});

export const Region = t.iface([], {
  "name": t.array("Name"),
  "region_id": "string",
  [t.indexKey]: "any",
});

export const Name = t.iface([], {
  "language": "string",
  "text": "string",
  [t.indexKey]: "any",
});

export const Version = t.lit("3.0");

const exportedTypeSuite: t.ITypeSuite = {
  SystemRegions,
  Data,
  Region,
  Name,
  Version,
};
export default exportedTypeSuite;
