name: Build and Deploy Java Language Bindings

on:
  push:
    branches:
      - master
      - feat/109-java-language-bindings
    paths:
      - "models/java/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./models/java

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Load secrets from 1Password
        id: onepw_secrets
        uses: 1password/load-secrets-action@v1.3.1
        with:
          export-env: true # Export loaded secrets as environment variables
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }} # This is required to connect to the vault in our 1Password account.
          MAVEN_GPG_PRIVATE_KEY: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/yztcx47yzp4vizjyaq7ulvkgoi/Private Key"
          MAVEN_GPG_PASSPHRASE: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/yztcx47yzp4vizjyaq7ulvkgoi/password"
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: ${{ env.MAVEN_USERNAME }}
          server-password:  ${{ env.MAVEN_PASSWORD }}
          gpg-private-key:  ${{ env.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase:  ${{ env.MAVEN_GPG_PASSPHRASE }}
    
      - name: Build and package
        run: |
          mvn install -pl rule-factory

      - name: Deploy with Maven
        run: mvn -B clean deploy -pl gbfs-java-model -Pci-cd
          
