name: GBFS Golang Language Bindings - PR Check

on:
    pull_request:
      branches: 
          - master
      paths:
          - "models/golang/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Run tests
      run: |
        cd models/golang/tests
        go test -v