name: Basic validation of examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    default:
      run:
        # Most of the boilerplate is in the "tests" folder
        working-directory: tests
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve Python version to be used
      id: python_version_check
      run: echo ::set-output name=PYTHON_VERSION::$(cat .python-version)
    - name: Install correct Python version
      uses: actions/setup-python@v2
      with:
        python-version: "${{ steps.python_version_check.outputs.PYTHON_VERSION }}"
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: pip install -r requirements.txt
