name: GBFS Typescript Language Bindings - Publish

on:
    push:
      branches:
        - master
      paths:
        - "models/typescript/**"
jobs:
    build-publish:
        name: build-publish-job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
                registry-url: 'https://registry.npmjs.org'
    
            - name: Install dependencies
              run: |
                cd ./scripts
                yarn
                cd ../models/typescript
                yarn
    
            - name: Publish to npm
              run: cd ./models/typescript && npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
                