name: GBFS Typescript Language Bindings - PR Check
on:
  push:
    branches:
        - feat/publish-gbfs-language-binding-workflow
  pull_request:
    branches: 
        - main
    paths:
      - "models/typescript/**"
    
jobs:
    check-versions:
        name: check-version-job
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Get local branch package.json version
              id: get_local_version
              run: |
                version=$(jq -r '.version' models/typescript/package.json)
                echo "::set-output name=version::$version"
          
            - name: Get master branch package.json version
              id: get_master_version
              run: |
                git fetch origin master
                master_version=$(git show origin/master:models/typescript/package.json | jq -r '.version')
                echo "::set-output name=master_version::$master_version"
          
            - name: Compare versions
              run: |
                local_version="${{ steps.get_local_version.outputs.version }}"
                master_version="${{ steps.get_master_version.outputs.master_version }}"
                if [ "$local_version" != "$master_version" ]; then
                    echo "Local branch version ($local_version) is different from master branch version ($master_version)"
                else
                    echo "Local branch version ($local_version) is the same as master branch version ($master_version)"
                    exit 1
                fi
    