name: GBFS Typescript Language Bindings - Publish

on:
    workflow_dispatch:
    workflow_call:
    push:
      branches:
        - master
      paths:
        - "models/typescript/**"

# Npm authentication via OpenID Connect (OIDC)
# https://docs.npmjs.com/trusted-publishers
permissions:
    id-token: write  # Required for OIDC
    contents: read
  
jobs:
    build-publish:
        name: build-publish-job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
                registry-url: 'https://registry.npmjs.org'
    
            - name: Install dependencies
              run: |
                cd ./scripts
                yarn
            
            # Ensure npm 11.5.1 or later is installed for OIDC support
            - name: Update npm
              run: npm install -g npm@11.6.2
      
            - name: Publish to npm
              run: cd ./models/typescript && npm publish
                
