name: GBFS Typescript Language Bindings - Publish

on:
    workflow_dispatch:
    workflow_call:
    push:
      branches:
        - master
      paths:
        - "models/typescript/**"
jobs:
    build-publish:
        name: build-publish-job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18'
                registry-url: 'https://registry.npmjs.org'
    
            - name: Install dependencies
              run: |
                cd ./scripts
                yarn

            - name: Load secrets from 1Password
              uses: 1password/load-secrets-action@v2.0.0
              with:
                export-env: true # Export loaded secrets as environment variables
              env:
                OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
                NODE_AUTH_TOKEN: "op://rbiv7rvkkrsdlpcrz3bmv7nmcu/ppzc4jxrwkf3omdmcs7z2wiwum/credential"
      
            - name: Publish to npm
              run: cd ./models/typescript && npm publish
              env:
                NODE_AUTH_TOKEN: ${{ env.NODE_AUTH_TOKEN }}
                
